/**
 * Per-faction tempo and opening strategies distilled from AsyncTI4 per-move records.
 * Auto-generated by scripts/distill_tempo.py — DO NOT EDIT DIRECTLY.
 */
import type { FactionId } from '../engine/types'

export interface FactionTempo {
  gamesCount: number
  gamesWon: number
  techOrder: { first: string[]; second: string[]; third: string[] }
  round1ScTop: string[]
  expansionRatio: number
  aggression: number
  avgResearchRound: number
}

export interface TempoData {
  [faction: string]: FactionTempo
}

export const TEMPORAL_DATA: Readonly<TempoData> = {
  "letnev": {
    "gamesCount": 228,
    "gamesWon": 35,
    "techOrder": {
      "first": [
        "dn2",
        "gd",
        "nes",
        "dd2",
        "x89c4"
      ],
      "second": [
        "fl",
        "lwd",
        "nes",
        "cv2",
        "asc"
      ],
      "third": [
        "dn2",
        "fl",
        "td",
        "asc"
      ]
    },
    "round1ScTop": [
      "imperial",
      "leadership"
    ],
    "expansionRatio": 0.581,
    "aggression": 0.419,
    "avgResearchRound": 0.0
  },
  "winnu": {
    "gamesCount": 145,
    "gamesWon": 34,
    "techOrder": {
      "first": [
        "amd",
        "det",
        "ps",
        "pds2",
        "pa"
      ],
      "second": [
        "pds2",
        "ps",
        "fl",
        "lwd",
        "asc"
      ],
      "third": [
        "cv2",
        "pds2",
        "ps",
        "aida"
      ]
    },
    "round1ScTop": [
      "construction",
      "imperial"
    ],
    "expansionRatio": 0.63,
    "aggression": 0.37,
    "avgResearchRound": 0.0
  },
  "nekro": {
    "gamesCount": 196,
    "gamesWon": 37,
    "techOrder": {
      "first": [
        "gd",
        "cv2",
        "amd",
        "st",
        "lwd"
      ],
      "second": [
        "gd",
        "amd",
        "x89c4",
        "sr",
        "dn2"
      ],
      "third": [
        "gd",
        "lwd",
        "x89c4",
        "cv2",
        "amd"
      ]
    },
    "round1ScTop": [
      "diplomacy"
    ],
    "expansionRatio": 0.667,
    "aggression": 0.333,
    "avgResearchRound": 0.0
  },
  "sardakk": {
    "gamesCount": 209,
    "gamesWon": 26,
    "techOrder": {
      "first": [
        "cv2",
        "exo2",
        "inf2",
        "dd2",
        "ws"
      ],
      "second": [
        "cv2",
        "dd2",
        "exo2",
        "inf2",
        "ff2"
      ],
      "third": [
        "inf2",
        "ff2",
        "exo2",
        "dd2",
        "pds2"
      ]
    },
    "round1ScTop": [
      "leadership"
    ],
    "expansionRatio": 0.571,
    "aggression": 0.429,
    "avgResearchRound": 0.0
  },
  "yssaril": {
    "gamesCount": 203,
    "gamesWon": 52,
    "techOrder": {
      "first": [
        "sd2",
        "bs",
        "inf2",
        "mi",
        "ff2"
      ],
      "second": [
        "ps",
        "sd2",
        "gd",
        "ff2",
        "mi"
      ],
      "third": [
        "ff2",
        "x89c4",
        "dn2",
        "pds2",
        "cr2"
      ]
    },
    "round1ScTop": [],
    "expansionRatio": 0.617,
    "aggression": 0.383,
    "avgResearchRound": 0.0
  },
  "mentak": {
    "gamesCount": 158,
    "gamesWon": 20,
    "techOrder": {
      "first": [
        "pds2",
        "cr2",
        "sd2",
        "x89c4",
        "da"
      ],
      "second": [
        "sd2",
        "ws",
        "mc",
        "inf2",
        "dn2"
      ],
      "third": [
        "x89c4",
        "cr2",
        "lwd",
        "ff2",
        "ws"
      ]
    },
    "round1ScTop": [],
    "expansionRatio": 0.659,
    "aggression": 0.341,
    "avgResearchRound": 0.0
  },
  "arborec": {
    "gamesCount": 217,
    "gamesWon": 41,
    "techOrder": {
      "first": [
        "lw2",
        "pds2",
        "st",
        "gd",
        "x89c4"
      ],
      "second": [
        "lw2",
        "ps",
        "x89c4",
        "gd",
        "pds2"
      ],
      "third": [
        "pds2",
        "amd",
        "nm",
        "dd2",
        "cv2"
      ]
    },
    "round1ScTop": [
      "imperial"
    ],
    "expansionRatio": 0.597,
    "aggression": 0.403,
    "avgResearchRound": 0.0
  },
  "muaat": {
    "gamesCount": 209,
    "gamesWon": 40,
    "techOrder": {
      "first": [
        "mr",
        "pds2",
        "gd",
        "pws2",
        "sd2"
      ],
      "second": [
        "x89c4",
        "gd",
        "pds2",
        "sd2",
        "mr"
      ],
      "third": [
        "mr",
        "pws2",
        "st",
        "det"
      ]
    },
    "round1ScTop": [
      "technology",
      "warfare"
    ],
    "expansionRatio": 0.549,
    "aggression": 0.451,
    "avgResearchRound": 0.0
  },
  "xxcha": {
    "gamesCount": 177,
    "gamesWon": 26,
    "techOrder": {
      "first": [
        "ps",
        "pds2",
        "det",
        "sd2",
        "nf"
      ],
      "second": [
        "pds2",
        "ps",
        "nf",
        "ws",
        "dn2"
      ],
      "third": [
        "pds2",
        "sd2",
        "ps",
        "x89c4",
        "inf2"
      ]
    },
    "round1ScTop": [
      "warfare",
      "leadership"
    ],
    "expansionRatio": 0.713,
    "aggression": 0.287,
    "avgResearchRound": 0.0
  },
  "sol": {
    "gamesCount": 234,
    "gamesWon": 48,
    "techOrder": {
      "first": [
        "ac2",
        "gd",
        "ff2",
        "sd2",
        "x89c4"
      ],
      "second": [
        "ac2",
        "ff2",
        "x89c4",
        "so2",
        "sd2"
      ],
      "third": [
        "x89c4",
        "ff2"
      ]
    },
    "round1ScTop": [],
    "expansionRatio": 0.6,
    "aggression": 0.4,
    "avgResearchRound": 0.0
  },
  "l1z1x": {
    "gamesCount": 198,
    "gamesWon": 38,
    "techOrder": {
      "first": [
        "sdn2",
        "gd",
        "x89c4",
        "sdn",
        "amd"
      ],
      "second": [
        "pds2",
        "asc",
        "fl",
        "aida",
        "inf2"
      ],
      "third": [
        "pds2",
        "md",
        "sdn2",
        "ff2",
        "asc"
      ]
    },
    "round1ScTop": [
      "construction",
      "imperial"
    ],
    "expansionRatio": 0.59,
    "aggression": 0.41,
    "avgResearchRound": 0.0
  },
  "yin": {
    "gamesCount": 202,
    "gamesWon": 38,
    "techOrder": {
      "first": [
        "x89c4",
        "cv2",
        "yso",
        "sd2",
        "det"
      ],
      "second": [
        "x89c4",
        "ff2",
        "sd2",
        "sr",
        "asc"
      ],
      "third": [
        "lwd",
        "dn2",
        "dd2",
        "da",
        "cv2"
      ]
    },
    "round1ScTop": [],
    "expansionRatio": 0.623,
    "aggression": 0.377,
    "avgResearchRound": 0.0
  },
  "saar": {
    "gamesCount": 238,
    "gamesWon": 38,
    "techOrder": {
      "first": [
        "ffac2",
        "gd",
        "cm",
        "st",
        "cv2"
      ],
      "second": [
        "ffac2",
        "lwd",
        "dn2",
        "fl",
        "ff2"
      ],
      "third": [
        "asc",
        "cv2",
        "ie",
        "x89c4",
        "ffac2"
      ]
    },
    "round1ScTop": [
      "diplomacy",
      "imperial"
    ],
    "expansionRatio": 0.492,
    "aggression": 0.508,
    "avgResearchRound": 0.0
  },
  "jolnar": {
    "gamesCount": 196,
    "gamesWon": 35,
    "techOrder": {
      "first": [
        "pds2",
        "sd2",
        "gd",
        "dn2",
        "ers"
      ],
      "second": [
        "pds2",
        "sd2",
        "dn2",
        "asc",
        "lwd"
      ],
      "third": [
        "cv2",
        "dn2",
        "sd2",
        "pds2",
        "ff2"
      ]
    },
    "round1ScTop": [
      "technology",
      "warfare"
    ],
    "expansionRatio": 0.632,
    "aggression": 0.368,
    "avgResearchRound": 0.0
  },
  "hacan": {
    "gamesCount": 211,
    "gamesWon": 34,
    "techOrder": {
      "first": [
        "sd2",
        "ws",
        "aida",
        "x89c4",
        "dn2"
      ],
      "second": [
        "sd2",
        "asc",
        "da",
        "dn2",
        "lwd"
      ],
      "third": [
        "dn2",
        "absol_pds2",
        "sd2",
        "qdn",
        "dd2"
      ]
    },
    "round1ScTop": [
      "imperial"
    ],
    "expansionRatio": 0.648,
    "aggression": 0.352,
    "avgResearchRound": 0.0
  },
  "naalu": {
    "gamesCount": 196,
    "gamesWon": 31,
    "techOrder": {
      "first": [
        "hcf2",
        "sd2",
        "fl",
        "cv2",
        "x89c4"
      ],
      "second": [
        "pds2",
        "sd2",
        "x89c4",
        "gd",
        "ps"
      ],
      "third": [
        "dd2",
        "ps",
        "inf2",
        "ws",
        "aida"
      ]
    },
    "round1ScTop": [
      "construction"
    ],
    "expansionRatio": 0.664,
    "aggression": 0.336,
    "avgResearchRound": 0.0
  }
} as const

export function getTechOrderPreference(faction: FactionId, position: 1 | 2 | 3, n: number = 3): string[] {
  const t = TEMPORAL_DATA[faction]?.techOrder
  if (!t) return []
  if (position === 1) return t.first.slice(0, n)
  if (position === 2) return t.second.slice(0, n)
  return t.third.slice(0, n)
}

export function getRound1ScTop(faction: FactionId, n: number = 3): string[] {
  return TEMPORAL_DATA[faction]?.round1ScTop?.slice(0, n) ?? []
}

export function getExpansionRatio(faction: FactionId): number {
  return TEMPORAL_DATA[faction]?.expansionRatio ?? 0.5
}

export function getAggression(faction: FactionId): number {
  return TEMPORAL_DATA[faction]?.aggression ?? 0.5
}
